# Generated by Django 4.1.1 on 2022-09-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='coordenacao',
            field=models.ManyToManyField(to='pessoa.professor', verbose_name='cordenacao'),
        ),
    ]
