# Generated by Django 4.1.1 on 2022-09-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_professor_alocado'),
        ('curso', '0002_curso_coordenacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='coordenacao',
        ),
        migrations.AddField(
            model_name='curso',
            name='coordenador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Cordenador', to='pessoa.professor'),
            preserve_default=False,
        ),
    ]
