# Generated by Django 4.1.1 on 2022-09-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_curso_coordenacao'),
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='alocado',
            field=models.ManyToManyField(to='curso.curso', verbose_name='Alocado'),
        ),
    ]
