# Generated by Django 4.1.1 on 2022-09-29 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0001_initial'),
        ('pessoa', '0002_professor_alocado'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='turma.turma'),
            preserve_default=False,
        ),
    ]
