# Generated by Django 4.1.1 on 2022-09-29 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_aluno_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='turma',
        ),
    ]
