# Generated by Django 4.1.1 on 2022-09-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0001_initial'),
        ('pessoa', '0005_aluno_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='turma',
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ManyToManyField(related_name='Aluno_Turma', to='turma.turma'),
        ),
    ]
