# Generated by Django 4.1.1 on 2022-10-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0001_initial'),
        ('pessoa', '0006_remove_aluno_turma_aluno_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.ManyToManyField(blank=True, related_name='Aluno_Turma', to='turma.turma'),
        ),
    ]
