# Generated by Django 4.1.1 on 2022-09-23 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('diaSemana', models.IntegerField()),
                ('horarios', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.FloatField()),
                ('nota2', models.FloatField()),
                ('notaProvaFinal', models.FloatField()),
                ('frequencia', models.IntegerField()),
                ('alunos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pessoa.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='turma.turma')),
            ],
        ),
    ]
