# Generated by Django 4.1.1 on 2022-09-23 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('cargaHoraria', models.IntegerField()),
                ('ementa', models.CharField(max_length=2000)),
                ('bibliografia', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='PreRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='disciplina', to='disciplina.disciplina')),
                ('preRequisito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='preRequisito', to='disciplina.disciplina')),
            ],
        ),
    ]
